### ISSUE TITLE
acx copy not preserving order of files and making non bootable disk

### ISSUE THREAD

**Issue by markjfisher** [AppleCommander/AppleCommander#107]
Hi,

First, a disclaimer: my knowledge of apple2 and its disks are on Day 2, I started looking at it yesterday, so forgive me for any assumptions I'm making that are incorrect!

I'm trying to use https://prodos8.com/bitsy-boot/ with prodos 2.4.2, and it requires files to be add in a specific order.

However, acx, doesn't appear to be preserving the file order specified on the command line.

```shell
$ acx create -d d1b.po --prodos
$ acx copy -d d1b.po --from ProDOS_2_4_2.dsk PRODOS BITSY.BOOT QUIT.SYSTEM BASIC.SYSTEM
$ acx list -d d1b.po --native

File: d1b.po
Name: /NEW.DISK/
* BITSY.BOOT      SYS      001 09/21/2023 01/13/2018        365 A=$2000
* QUIT.SYSTEM     SYS      001 09/21/2023 01/13/2018         56 A=$2000
* BASIC.SYSTEM    SYS      021 09/21/2023 01/13/2018     10,240 A=$2000
* PRODOS          SYS      035 09/21/2023 01/13/2018     17,128
ProDOS format; 110,080 bytes free; 33,280 bytes used.
```

Repeating the above with any order of files gives the same order of files, with PRODOS at the end.

When I boot this disk in AppleWin, it comes up with a graphic moving around the screen saying it's made with AppleCommander, and to insert a disk and press a key.

The only way I've been able to get this working is as follows:

```shell
$ acx create -d d1b.po --prodos -f ProDOS_2_4_2.dsk
$ acx delete -d d1b.po -f BASIC.SYSTEM
$ acx copy -d d1b.po --from ProDOS_2_4_2.dsk BITSY.BOOT
$ acx copy -d d1b.po --from ProDOS_2_4_2.dsk QUIT.SYSTEM
$ acx copy -d d1b.po --from ProDOS_2_4_2.dsk BASIC.SYSTEM
$ acx ls -d d1b.po

File: d1b.po
Name: /NEW.DISK/
* PRODOS          SYS      035 09/21/2023 01/13/2018     17,128
* BITSY.BOOT      SYS      001 09/21/2023 01/13/2018        365 A=$2000
* QUIT.SYSTEM     SYS      001 09/21/2023 01/13/2018         56 A=$2000
* BASIC.SYSTEM    SYS      021 09/21/2023 01/13/2018     10,240 A=$2000
ProDOS format; 110,080 bytes free; 33,280 bytes used.
```

which then boots correctly in AppleWin, showing the BITSY menu.

Is there a better way to do this? I fortunately happened upon the workaround, but wonder if this is more my lack of knowledge of apple and prodos formatting.

I also found that creating an initial empty disk, and copying just PRODOS onto it doesn't work (gives the AC logo and asks for disk), see the following.

```shell
# this doesn't boot correctly
$ acx create -d d1b.po --prodos
$ acx copy -d d1b.po --from ProDOS_2_4_2.dsk PRODOS
```

```shell
# this does boot to dos correctly
$ acx create -d d1b.po --prodos -f ProDOS_2_4_2.dsk
$ acx delete -d d1b.po -f BASIC.SYSTEM
```

using `acx ls` on both generated files shows the same files, but the first one doesn't seem to boot correctly.

I couldn't see any other `acx` sub commands that might fix this.
The 2 resultant files are vastly different from a diff point of view, and the `compare` subcommand also says the differ in their blocks:

```shell
$ acx compare -d d1b-broke.po --block d1b-working.po
The disks do not match.
Block #0 does not match.
Block #2 does not match.
Blocks #42-62 do not match.
```

Many thanks!

**Comment by ryandesign** [comment]
> acx, doesn't appear to be preserving the file order specified on the command line

That seems like a reasonable expectation. Maybe AppleCommander is slurping all of the remaining command line arguments (the filenames) into a hash (which would have a predictable order but not any particular guaranteed order) and is then iterating the hash. I don't know Java so I don't know where in the source code to look to confirm that guess.


> creating an initial empty disk, and copying just PRODOS onto it doesn't work

That's not surprising. An Apple II disk does not become bootable by placing some files on it. It becomes bootable by having its boot sectors filled with the boot code, which AppleCommander will do if you tell it to make a bootable disk and won't do otherwise.

The description of the `-f` flag from `acx create --help` is:

```
  -f, --format=<formatSource>
                           Disk to copy system files/tracks/boot sector from.
```

So if you don't tell it where to copy the boot sectors from, it won't do it, and the disk won't be bootable.

In addition to the boot sectors, ProDOS uses some files like the PRODOS file, perhaps leading you to the impression that that file is the entirety of the disk operating system when it's actually only a part of it. It's clearer with DOS where there are no extra files and the disk operating system is contained entirely within the boot sectors.

**Comment by a2geek** [comment]
@ryandesign is correct. AppleCommander basically copies the files as it finds them on the disk and not in the order you specify.

You can simplify the creation a little bit by copying those system files all together:
```
$ acx create -d mynewdisk.po --prodos --format ~/Downloads/ProDOS_2_4_2.dsk 
$ acx rm -d mynewdisk.po -f BASIC.SYSTEM
$ acx cp -d mynewdisk.po --from ~/Downloads/ProDOS_2_4_2.dsk BITSY.BOOT QUIT.SYSTEM BASIC.SYSTEM
$ acx ls -d mynewdisk.po 

File: mynewdisk.po
Name: /NEW.DISK/
* PRODOS          SYS      035 10/26/2023 01/13/2018     17,128          
* BITSY.BOOT      SYS      001 10/26/2023 01/13/2018        365 A=$2000  
* QUIT.SYSTEM     SYS      001 10/26/2023 01/13/2018         56 A=$2000  
* BASIC.SYSTEM    SYS      021 10/26/2023 01/13/2018     10,240 A=$2000  
ProDOS format; 110,080 bytes free; 33,280 bytes used.
```

Note that the order (as well as `PRODOS` being at the end) was due to the ProDOS disk:
```
$ acx ls -d ~/Downloads/ProDOS_2_4_2.dsk 

File: /home/rob/Downloads/ProDOS_2_4_2.dsk
Name: /PRODOS.2.4.2/
  VIEW.README     BAS      001 09/15/2016 01/13/2018        512 A=$0801  
* BITSY.BOOT      SYS      001 09/15/2016 01/13/2018        365 A=$2000  
* QUIT.SYSTEM     SYS      001 09/15/2016 01/13/2018         56 A=$2000  
* BASIC.SYSTEM    SYS      021 08/30/2016 01/13/2018     10,240 A=$2000  
* COPYIIPLUS.8.4  SYS      056 02/28/1989 01/13/2018     28,114 A=$2000  
* CAT.DOCTOR      SYS      028 02/22/1990 01/13/2018     13,583 A=$2000  
* ADTPRO2.0.2     SYS      001 11/13/2016 01/13/2018        348 A=$2000  
* FASTDSK.SYSTEM  SYS      004 05/04/2009 01/13/2018      1,402 A=$2000  
* UNSHRINK        SYS      026 10/13/1990 01/13/2018     12,468 A=$2000  
* BLOCKWARDEN     SYS      020 02/21/1990 01/13/2018      9,264 A=$2000  
* MR.FIXIT.Y2K    SYS      019 04/06/1999 01/13/2018      9,027          
  MAKE.SMALL.P8   BAS      001 01/18/2018 01/13/2018        357 A=$0801  
  MINIBAS         SYS      001 09/16/2016 01/13/2018        496          
* ADTPRO2.0.2.BIN BIN      029 11/13/2016 01/13/2018     14,196 A=$0800  
* CD.EXT          $F1      011 02/22/1990 01/13/2018      4,864          
* FASTDSK         BIN      019 05/04/2009 01/13/2018      8,960 A=$8E00  
  FASTDSK.CONF    BIN      001 09/08/2016 01/13/2018        512 A=$8C00  
  README          TXT      001 01/18/2018 01/13/2018        497          
* PRODOS          SYS      034 01/18/2018 01/13/2018     17,128          
ProDOS format; 0 bytes free; 143,360 bytes used.
```

Again, you cannot just `acx create -d newdisk.po --prodos` because AppleCommander doesn't really know _what_ version of ProDOS (or DOS or Pascal, etc) you want. It needs that format source to do this correctly.

**Comment by markjfisher** [comment]
Thanks for the explanation both. I did end up doing similar to what you suggest @a2geek :
https://github.com/markjfisher/fujinet-network-lib-tests/blob/master/apple-tools/mk-bitsy.sh#L32

I had a look at the source, I've used picocli quite a bit in my own projects. Hadn't realised it was the target's file system it was reading in the list, which would have made it easier to realise why it was ordering them as it was.
