### ISSUE TITLE
cannot put BAS files in disk images

### ISSUE THREAD

**Issue by fanfani** [AppleCommander/AppleCommander#23]
hello there, i'm going nuts trying to put BASIC programs in disk images.

let's say i write this simple program:

```
$ cat TEST.BAS 
10 REM BEGIN TEST
20 PRINT "JUST A TEST"
30 REM END TEST
```
create a new prodos disk image:

`$ java -jar AppleCommander-ac-1.4.0.jar -pro140 blank.po BLANK`

check image is ok:

```
$ java -jar AppleCommander-ac-1.4.0.jar -ls blank.po
blank.po /BLANK/
ProDOS format; 139.776 bytes free; 3.584 bytes used.
```

put the file inside the disk image:

`$ java -jar AppleCommander-ac-1.4.0.jar -p TEST bas < TEST.BAS`

check disk image again:

```
$ java -jar AppleCommander-ac-1.4.0.jar -ls blank.po
blank.po /BLANK/
TEST BAS 57  
ProDOS format; 139.264 bytes free; 4.096 bytes used.
```

but when i try to get file back in stdout i get:

```
$ java -jar AppleCommander-ac-1.4.0.jar -e blank.po TEST

Error: 57
java.lang.ArrayIndexOutOfBoundsException: 57
	at com.webcodepro.applecommander.util.ApplesoftTokenizer.getNextToken(Unknown Source)
	at com.webcodepro.applecommander.storage.filters.ApplesoftFileFilter.filter(Unknown Source)
	at com.webcodepro.applecommander.ui.ac.getFile(Unknown Source)
	at com.webcodepro.applecommander.ui.ac.main(Unknown Source)
```

reading the file from disk in any ameulator results in some long basic code (prodos header stuff?) starting with my code, which looks kind of crippled

if i get back raw data i get back my file: 

```
$ java -jar AppleCommander-ac-1.4.0.jar -g blank.po TEST
10 REM BEGIN TEST
20 PRINT "JUST A TEST"
30 REM END TEST
```

what is going on?

...am i missing something? file should be tokenized somehow? should i add starting address?

did not find any helpful hint reading the docs

thank you

PS
putting binary files in disk images works as expected

i am using linux with Oracle java version 1.8.0_161

**Comment by a2geek** [comment]
You're giving AppleCommander a bit too much credit. ;-)

The file in Linux is a text file.  When you placed it onto the disk, `ac` does not do any processing of it and essentially shoved a text file into what ProDOS thinks is a `BAS` program.

When the `-e` flag is used, `ac` tries to export the program in a sensible manner. For `BAS` it decodes the tokenized Applesoft program and writes it as text on your machine.  Since it was already text, it (obviously) doesn't detokenize very well.

When the `-g` flag is used, `ac` just pulls the raw data and writes it to your machine as-is.

I recall seeing or reading about a program that can tokenize a text file, but I'm drawing a blank, unfortunately... if I can recall/find it in the next few days, I'll post a link!

**Comment by a2geek** [comment]
Absolutely!  Is this something you wanted to work on yourself?  I'm more than willing to accept submissions. 

I'm thinking that as a first stab, the assumption is that the AppleSoft code is "well formed".  We don't need to mash our code into a single line any more, so spaces (literally!) aren't at a premium any more.  I see that there are notes about special handling for `AT`/`ATN` (and more, I think). Requiring spaces between stuff would probably greatly simplify the effort.
