### ISSUE TITLE
[Crash, 1.6.0] CP/M Volume

### ISSUE THREAD

**Issue by ZoriaRPG** [AppleCommander/AppleCommander#41]
Using Apple Commander, Windows 1.6.0 with Java 8:

I loaded the CP/M Spellbinder disk image (https://ftp.apple.asimov.net/images/cpm/productivity/SpellBinderCPM.dsk), with the intent to modify it.

When I right-click on a file, and select 'delete', AC crashes. 

Further, when I create  new CP/M image, the option to import files is deselected.

**Comment by a2geek** [comment]
Hey @ZoriaRPG - I just took a look and confirmed that delete is definitely non-functional here. 

From my quick peek, the issue is that the filename is broken into FILENAME.EXT and AppleCommander really doesn't know how to handle that. Everything else is setup to handle just FILENAME. I suspect this can be fixed, however...

As far as adding files to the disk, AppleCommander doesn't support writing content to a CP/M disk at this time; it's really just read-only. 

Why is delete available? I'm guessing because it looked "simple". :man_shrugging:

**Comment by a2geek** [comment]
I made some code changes that resolve the crash. From what I can tell, this is working as expected.  I deleted a file, which essentially sets the "user" to 0xe5.

If you wanted to review, feel free to pull from master and give it a whirl!
