### ISSUE TITLE
Crash when adding files to a disk image that is or was full

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#58]
Using the AppleCommander 1.6.0 GUI on macOS 10.13.6 I created a DOS 3.3 DOS order disk image.

If I try to add files to the disk image that will occupy more space than is available on the disk image, AppleCommander quits immediately when I press the Finish button in the Import dialog. It should instead tell me the disk is out of space and remain open so that I can correct the problem.

If I delete existing files on the disk and then try to add a new file, it quits just the same, even though there should now be enough space. It should instead add the files to the disk and not quit.

**Comment by a2geek** [comment]
This will be fixed with the next version of AppleCommander. Good find! As far as I can determine, it's been there for more than a decade at this point!  The issue was with the text lookups -- the keys didn't exist, and, they had simply been entered incorrectly. I did change the error message to at least identify what was missing for any future items as well. (If it happened once, I'm certain it's happened a couple of others as well.)

**Comment by a2geek** [comment]
I forgot to add the ticket number. This is the commit: https://github.com/AppleCommander/AppleCommander/commit/366c921ed56ba02192e58f500aa773c50fa0f5bb
