### ISSUE TITLE
AppleSingle issues (files without data fork, real name, modification date)

### ISSUE THREAD

**Issue by gravaigu** [AppleCommander/AppleCommander#84]
Hi,

I'm currently writing a program to extract data from Salvation Bakkup disc images. The goal is to recreate a ProDOS image of the original backed up hard drive, with all the files, directories, and complete ProDOS file informations, storage type, dates etc. The program generates AppleSingle files with entries 1 (data), 2 (resource, when needed), 3 (real name), 8 (file dates info) and 11 (ProDOS file info). acx is then invoked to create the drive image, directories structure, and import the AppleSingle files.

Everything works fine, except when putting files with a resource fork and 0 byte long data fork (e.g. SYSTEM/SYSTEM.SETUP/Sys.Resources). The file is rejected with the following exception:
`java.io.IOException: This AppleSingle does not contain a data fork.`
Actually, the AppleSingle file does contain a data fork, but it is empty (length==0).

Other minor issues encountered so far:

- Entry 3 (Real Name): case seems to be ignored (all file names are uppercase when imported).
- Entry 8 (File Dates Info): Creation date is used, but Modification date is ignored (all files have the system date as modification date). Is it possible to use the modification date instead?

I would gladly contribute and help to fix these issues if possible. Thanks in advance, Eric

**Comment by a2geek** [comment]
More than willing to take PR's if you want to work this!

A couple of thoughts...
* AppleCommander's API doesn't really support Resource Forks, but I did notice that support was added to `ProdosFormatDisk` [here](https://github.com/AppleCommander/AppleCommander/blob/7bb1408b3a68454c1022edf4a11b6d626d0b00fe/lib/ac-api/src/main/java/com/webcodepro/applecommander/storage/os/prodos/ProdosFormatDisk.java#L758). Hopefully that can just be reused, especially since it looks to have gotten really messy. Actually, `ProdosFileEntry` does have a useful [method here](https://github.com/AppleCommander/AppleCommander/blob/7bb1408b3a68454c1022edf4a11b6d626d0b00fe/lib/ac-api/src/main/java/com/webcodepro/applecommander/storage/os/prodos/ProdosFileEntry.java#L518).
* For the AppleSingle support, that is provided by the [applesingle](https://github.com/AppleCommander/applesingle) project. I'd confirm that the utility program does see all the pieces of the AppleSingle file. Based on the `asu` command writeup [here](https://github.com/AppleCommander/applesingle/tree/master/tools/asu) I suspect it does. But better be safe than sorry!

**Comment by gravaigu** [comment]
Thank you for your prompt answer. I have made testing with the `asu` command on the suspected file, and in fact it triggers errors on the fact that the data fork is empty. As that should not be the case (GS/OS system disks contain such files), I've filled an issue with the applesingle project. When the issue is closed I will report here and see if I can improve the code.

**Comment by a2geek** [comment]
Looking at this, I'm finding the routine that handles resource forks doesn't appear to work (or work as expected at any rate). I'm also trying to make `acx` a bit smarter about upper/lower case names.

**Comment by a2geek** [comment]
This should get you closer. The resource fork is created and the names should be set with mixed case.

[AppleCommander-acx-1.9.0-SNAPSHOT.zip](https://github.com/AppleCommander/AppleCommander/files/8986777/AppleCommander-acx-1.9.0-SNAPSHOT.zip)

**Comment by a2geek** [comment]
Let me know if that resolves the issue for you. I think I'll take some time to refactor the code. I think the API needs to be updated to support resource forks -- it can be written but not read at this point. (File this under things I knew nothing about when I started!)

**Comment by gravaigu** [comment]
Great! I'm going to test this, and report here, as soon as I have a couple of hours this week.

**Comment by gravaigu** [comment]
I've done some testing (with 1248 Applesingle files). First impressions:
- The names respect the mixed case naming from the Real Name entry (ID=3)
- The resource fork (entry ID 2) is created
- The files with no data fork are created

I'll try to do more testing on the files content and attributes, but for me these issues seem to be solved. Great 👍 :-)

Still, I've noticed 2 remaining issues (first one already discussed before):
- The file modification date set in entry ID 8 is not used (instead the modification date is set to the system date). As I am building an archive restauration tool, this is an issue for me. Maybe this different behavior could be chosen with a command arg?
- The ProDOS auxiliary type field from entry ID 11 is not used. The created file always has a $0000 auxiliary type, whatever is put in entry ID 11.

As an example, find attached an Applesingle file with auxiliary type $0102 and modification date 06/14/1989 09:07.

[AppleDisk3.zip](https://github.com/AppleCommander/AppleCommander/files/9000510/AppleDisk3.zip)

**Comment by gravaigu** [comment]
Note that I have released on github my Python scripts that extract files from ProSel-16 Backup floppies as AppleSingle, and use *acx* to put the files hierarchy on a ProDOS disk. See my project here: https://github.com/gravaigu/ProSel-Tools
